// <auto-generated />
using Integration_library.Pharmacy.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Integration_library.Migrations
{
    [DbContext(typeof(PharmacyDbContext))]
    [Migration("20211106160556_pharmacyMigration")]
    partial class pharmacyMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Integration_library.Pharmacy.Model.Pharmacy", b =>
                {
                    b.Property<string>("PharmacyName")
                        .HasColumnType("text");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text");

                    b.HasKey("PharmacyName");

                    b.ToTable("Pharmacies");
                });
#pragma warning restore 612, 618
        }
    }
}
